import { useState } from "react";
import type { TableListItem } from "../api/types";

// Default preview length for the collapsed description. Cards in the table
// list use a smaller value (set via the prop); the per-table banner gets
// more horizontal room and can show more text before truncating.
const DEFAULT_PREVIEW_CHARS = 280;

interface TableDescriptionProps {
  description: string | null | undefined;
  /** Soft character cap for the collapsed view. */
  previewChars?: number;
  /** Body class — banner / card styling differ but the markup matches. */
  className?: string;
  /** Placeholder when description is missing. Defaults to "no description". */
  emptyText?: string;
}

/**
 * Description renderer with an inline "more / less" toggle. Strips the
 * autogenerated `[Note: ...]` foreign-key suffix that CAVE appends to
 * most table descriptions when collapsed — the human prose comes first;
 * expanded view shows everything.
 */
export function TableDescription({
  description,
  previewChars = DEFAULT_PREVIEW_CHARS,
  className,
  emptyText = "no description",
}: TableDescriptionProps) {
  const [expanded, setExpanded] = useState(false);
  const clean = (description ?? "").trim();

  if (!clean) {
    return <p className={`${className ?? ""} empty`}>{emptyText}</p>;
  }

  const previewBase = clean.replace(/\s*\[Note:[^\]]*\]\s*$/i, "");
  const needsTruncate = previewBase.length > previewChars;
  const preview = expanded
    ? clean
    : needsTruncate
      ? `${previewBase.slice(0, previewChars).trimEnd()}…`
      : previewBase;

  return (
    <p className={className}>
      {preview}
      {needsTruncate && (
        <button
          type="button"
          className="link-button"
          onClick={() => setExpanded((v) => !v)}
        >
          {expanded ? " less" : " more"}
        </button>
      )}
    </p>
  );
}

interface TableMetadataBannerProps {
  /** Metadata for the currently-displayed table, or null while the
   *  cached list query is still loading / failed. The banner stays mounted
   *  either way so the page header doesn't reflow when metadata arrives. */
  item: TableListItem | null;
  /** Fallback name shown when item hasn't loaded yet — pulled from the URL
   *  so the title is correct on first paint. */
  fallbackName: string;
  /** Optional schema-type click handler. The list view's card uses this to
   *  set the search filter; the per-table view doesn't have a list to filter,
   *  so this is omitted there and the chip renders as static text. */
  onSchemaClick?: (schema: string) => void;
}

/**
 * Header banner shown above the rows of a single table. Same metadata as the
 * list cards but laid out horizontally as a page header rather than a tile.
 * Loading state: title from URL; chips/description appear when the list
 * query resolves. Item missing entirely (404'd from the list): renders just
 * the title — the rows query will still drive the actual table below.
 */
export function TableMetadataBanner({
  item,
  fallbackName,
  onSchemaClick,
}: TableMetadataBannerProps) {
  const name = item?.name ?? fallbackName;
  const kind = item?.kind ?? "table";

  return (
    <div className={`table-meta-banner kind-${kind}`}>
      <div className="table-meta-title">
        <h2>{name}</h2>
        {item && (
          <span className={`chip chip-kind chip-kind-${kind}`}>{kind}</span>
        )}
        {item?.schema_type && (
          onSchemaClick
            ? (
              <button
                type="button"
                className="chip chip-schema"
                onClick={() => onSchemaClick(item.schema_type!)}
                title={`Filter to ${item.schema_type} tables`}
              >
                {item.schema_type}
              </button>
            )
            : <span className="chip chip-schema">{item.schema_type}</span>
        )}
      </div>

      {item && (
        <TableDescription
          description={item.description}
          className="table-meta-desc"
          emptyText={kind === "view" ? "view (no description available)" : "no description"}
        />
      )}

      {item && (item.reference_table || item.row_count != null || item.voxel_resolution) && (
        <div className="table-meta-footer">
          {item.reference_table && (
            <span className="meta" title="reference table this points at">
              ↗ {item.reference_table}
            </span>
          )}
          {item.row_count != null && (
            <span className="meta">{item.row_count.toLocaleString()} rows</span>
          )}
          {item.voxel_resolution && (
            <span className="meta" title="voxel resolution (nm/voxel)">
              {item.voxel_resolution.join("×")} nm
            </span>
          )}
        </div>
      )}
    </div>
  );
}
